"""Data types and operations from DSS Auxiliary API 1.1.0 OpenAPI"""

# This file is autogenerated; do not modify manually!

from __future__ import annotations

from enum import Enum

from implicitdict import ImplicitDict, StringBasedDateTime

from uas_standards.utils import Operation

API_VERSION = "1.1.0"
"""Version of DSS Auxiliary API OpenAPI specification from which the objects in this package were generated."""


class VersionResponse(ImplicitDict):
    version: str
    """The version of the DSS."""


class ErrorResponse(ImplicitDict):
    message: str | None
    """Human-readable message indicating what error occurred and/or why."""


class PoolResponse(ImplicitDict):
    dar_id: str | None = ""
    """Identifier of the DSS Airspace Representation shared by the pool of DSS instances to which this DSS instance belongs. Each DSS instance participating in the pool should indicate the same DAR ID as this ID describes the DAR shared by the pool."""


class Heartbeat(ImplicitDict):
    timestamp: StringBasedDateTime
    """Time at which heartbeat was registered."""

    reporter: str | None = ""
    """Identity (via access token `sub` claim) of client reporting the heartbeat, or omitted if no client reported the heartbeat."""

    source: str
    """Source/trigger of this heartbeat."""

    index: int | None = 0
    """Index of this heartbeat within the set of all heartbeats for this pool participant."""

    next_heartbeat_expected_before: StringBasedDateTime | None = StringBasedDateTime("")
    """The time by which a new heartbeat should be registered for this DSS instance if the DSS instance operator's system is behaving correctly."""


class CAsResponse(ImplicitDict):
    CAs: list[str] | None
    """A list of certificates, each in PEM format."""


class SCDLockModeResponse(ImplicitDict):
    global_lock: bool | None
    """The value of the 'enable_scd_global_lock' option for this DSS instance"""


class DSSInstance(ImplicitDict):
    id: str
    """Identity of this DSS instance participating in the pool (locality)."""

    public_endpoint: str | None
    """Public endpoint of this DSS instance"""

    most_recent_heartbeat: Heartbeat | None
    """Most recent heartbeat registered for this DSS instance."""


class DSSInstancesResponse(ImplicitDict):
    dss_instances: list[DSSInstance] | None = []


class OperationID(str, Enum):
    GetVersion = "getVersion"
    ValidateOauth = "validateOauth"
    GetPool = "getPool"
    GetDSSInstances = "getDSSInstances"
    PutDSSInstancesHeartbeat = "putDSSInstancesHeartbeat"
    GetAcceptedCAs = "getAcceptedCAs"
    GetInstanceCAs = "getInstanceCAs"
    GetScdLockMode = "getScdLockMode"


OPERATIONS: dict[OperationID, Operation] = {
    OperationID.GetVersion: Operation(
        id="getVersion",
        path="/aux/v1/version",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: VersionResponse,
        },
    ),
    OperationID.ValidateOauth: Operation(
        id="validateOauth",
        path="/aux/v1/validate_oauth",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: None,
            401: ErrorResponse,
            403: ErrorResponse,
        },
    ),
    OperationID.GetPool: Operation(
        id="getPool",
        path="/aux/v1/pool",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: PoolResponse,
            401: ErrorResponse,
            403: ErrorResponse,
            501: ErrorResponse,
        },
    ),
    OperationID.GetDSSInstances: Operation(
        id="getDSSInstances",
        path="/aux/v1/pool/dss_instances",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: DSSInstancesResponse,
            401: ErrorResponse,
            403: ErrorResponse,
            501: ErrorResponse,
        },
    ),
    OperationID.PutDSSInstancesHeartbeat: Operation(
        id="putDSSInstancesHeartbeat",
        path="/aux/v1/pool/dss_instances/heartbeat",
        verb="PUT",
        request_body_type=None,
        response_body_type={
            201: DSSInstancesResponse,
            400: ErrorResponse,
            401: ErrorResponse,
            403: ErrorResponse,
            501: ErrorResponse,
        },
    ),
    OperationID.GetAcceptedCAs: Operation(
        id="getAcceptedCAs",
        path="/aux/v1/configuration/accepted_ca_certs",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: CAsResponse,
            501: ErrorResponse,
        },
    ),
    OperationID.GetInstanceCAs: Operation(
        id="getInstanceCAs",
        path="/aux/v1/configuration/ca_certs",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: CAsResponse,
            501: ErrorResponse,
        },
    ),
    OperationID.GetScdLockMode: Operation(
        id="getScdLockMode",
        path="/aux/v1/configuration/scd_lock_mode",
        verb="GET",
        request_body_type=None,
        response_body_type={
            200: SCDLockModeResponse,
            501: ErrorResponse,
        },
    ),
}
